### PR TITLE
formatted doc

### PR DESCRIPTION
**Pull request by adisuyash**
I have formatted and edited the README.md file .
Please review it @Dilli-Raj-Timalsina

### CODE REVIEW

**Comment by Dilli-Raj-Timalsina** [comment]
can you update your readme with below mentioned documentation , readme should include quick endpoint with required request body and parameters .
https://documenter.getpostman.com/view/23609125/2s93eWzCdf

**Comment by adisuyash** [comment]
I dont find the base URL for all API endpoints.
Please check whether 127.0.0.1:3000/api/v1/ is correct or not??

**Comment by Dilli-Raj-Timalsina** [comment]
you can use {{url}}/api/v1/   as a base url and remaining /course ,/student ,/teacher are resources .

**Comment by adisuyash** [comment]
I have added the API documentation.
Please review @Dilli-Raj-Timalsina

**Comment by Dilli-Raj-Timalsina** [comment]
It would be great if you could do the same for course resource as well .

**Comment by adisuyash** [comment]
Ok I will do the same for course resource as well

**Pull request merged**
